apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system-deployment
  labels:
    app: solar-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        image: moheie/solar-system:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          value: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
        - name: MONGO_USERNAME
          value: "superuser"
        - name: MONGO_PASSWORD
          value: "SuperPassword"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /live
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
